(* let parse_key_value parser = *)
(*   let parser = parser_next parser in *)
(*   if not (expect_type parser.curr TokenType.String) then ( *)
(*     Printf.printf "Expected token String for key but got `%s` instead.\n" (Option.get parser.curr).literal; *)
(*     parser, false *)
(*   ) *)

(*   else *)
(*     let parser = parser_next parser in *)
(*     if not (expect_type parser.curr TokenType.Colon) then ( *)
(*       Printf.printf "Expected token to be Colon but got `%s` instead.\n" (Option.get parser.curr).literal; *)
(*       parser, false *)
(*     ) *)

(*     else *)
(*       let parser = parser_next parser in *)
(*       if not (expect_type parser.curr TokenType.String) then ( *)
(*         Printf.printf "Expected token String for value but got `%s` instead.\n" (Option.get parser.curr).literal; *)
(*         parser, false *)
(*       ) *)

(*       else *)
(*         parser, true *)

(* let rec parse_object parser = *)
(*   let rec parse_body par = *)
(*     let par = parser_next par in (\* Curr should be the 'key' *\) *)
(*     if not (expect_type par.curr TokenType.String) then ( *)
(*       Printf.printf "Expected token String for key but got `%s` instead.\n" (Option.get par.curr).literal; *)
(*       par, false *)
(*     ) *)

(*     else *)
(*       let par = parser_next par in (\* Curr should be ':' *\) *)
(*       if not (expect_type par.curr TokenType.Colon) then ( *)
(*         Printf.printf "Expected token to be Colon but got `%s` instead.\n" (Option.get par.curr).literal; *)
(*         par, false *)
(*       ) *)

(*       else *)
(*         let par = parser_next par in (\* Curr should be the 'value' *\) *)
(*         (\* Only supports string value by now *\) *)
(*         if not (expect_type par.curr TokenType.String) then ( *)
(*           Printf.printf "Expected token String for value but got `%s` instead.\n" (Option.get par.curr).literal; *)
(*           par, false *)
(*         ) *)

(*         else *)
(*           (\* After key/value check *\) *)
(*           let par = parser_next par in *)
(*           if Option.is_none par.curr then ( *)
(*             print_endline "Unexpected end of object. Object is not closed"; *)
(*             par, false *)
(*           ) *)

(*           else *)
(*             match (Option.get par.curr).token_type with *)
(*             | TokenType.CloseBrace -> par, true *)
(*             | TokenType.Comma -> ( *)
(*                match par.peek with *)
(*                | None -> ( *)
(*                  print_endline "Unexpected end of object. Nothing after comma"; *)
(*                  par, false *)
(*                ) *)
(*                | Some token when token.token_type = TokenType.String -> *)
(*                   parse_body par (\* Recursive call to parse the next key/value pair *\) *)
(*                | _ -> ( *)
(*                  Printf.printf "Expected token String for key *)
(*                                 after token Comma but got `%s` instead." (Option.get par.curr).literal; *)
(*                  par, false *)
(*                ) *)
(*             ) *)
(*             | other_type -> ( *)
(*               Printf.printf "Unexpected token after key/value pair `%s`" (TokenType.to_string other_type); *)
(*               par, false *)
(*             ) *)
(*   in *)

(*   match parser.peek with *)
(*   | None -> ( print_endline "Unexpected end of object"; *)
(*               parser, false *)
(*             ) *)
(*   | Some token -> *)
(*      match token.token_type with *)
(*      | TokenType.CloseBrace -> parser, true *)
(*      | TokenType.String -> *)
(*         let parser, ok = parse_body parser in *)
(*         if not ok then *)
(*           parser, false *)
(*         else *)
(*           parse_object parser *)
(*      | TokenType.Unknown -> parser, false *)
(*      | _ -> failwith "Not covered in parse_object" *)
